version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:xenial
    resource_class: large
    dependencies:
      pre:
        - sudo apt-get update;sudo apt-get install -y sudo
    steps:
      - checkout
      - run:
          name: Build
          command: sudo ./build_linux64.sh