version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:xenial
    resource_class: large
    steps:
      - checkout
      - run: apt-get install -y sudo
      - run:
          name: Build
          command: sudo ./build_linux64.sh