version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:xenial
    resource_class: large
    working_directory: ~/nwjs-build
    steps:
      - checkout
      - run:
          name: Build
          command: ./build_linux64.sh